version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: sayz_user
      POSTGRES_PASSWORD: sayz_password
      POSTGRES_DB: sayz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: